config/routes.rb
Rails.application.routes.draw do
  

  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/index' => 'cart#index'
  get '/cart/:id' => 'cart#add'

  resources :products
  root 'home#index'

  get 'page/about'

  get 'page/faqs'

  get 'page/contact'
  post 'page/send_details'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :books 

  
resource :cart, only: [:show] do
  put 'add/:book_id', to: 'carts#add', as: :add_to
  put 'remove/:book_id', to: 'carts#remove', as: :remove_from
end

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :title, uniqueness: true
	
	validates :author, :price,
	:poster_url, presence: true
  validates_format_of :title, :author, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/

  

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


 def cart_count
  $redis.scard "cart#{id}" rescue nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
  #before_action :set_book, only: [:edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  # @cart_action = @book.cart_action current_user.try :id
end
  

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
       render :new 
    end
  end

  def update 
    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to @book, notice: 'Book was successfully updated.' 
    else
      render :edit 
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_url, notice: 'book was successfully deleted.' 
  end

def edit
  @book = Book.find(params[:id])
  render new_book_path if @book
end

  # GET /books/new
  
  # GET /books/1/edit
  
  # POST /books
  # POST /books.json
  
    def book_params
      params.require(:book).permit(:title, :author, :price, :poster_url)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
   def add
		id = params[:id]
		if session[:cart] then
			cart = session[:cart]
		else
			session[:cart] = {}
			cart = session[:cart]
		end
		if cart[id] then
			cart[id] = cart[id] + 1
		else
			cart[id] = 1
		end
		redirect_to :action => :index
	end

	def clearCart
		session[:cart] = nil
		redirect_to :action =>
		:index
	end

  def index
  	if session[:cart] then
  		@cart = session[:cart]
  	else
  		@cart = {}
  end
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to books_path
  	end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end

  def send_details
  	name = params[:name]
  	email = params[:email]
  	message = params[:message]
  	Usermailer.send_contact_details(name, email, message).deliver
  	redirect_to page_contact_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :author, :price, :poster_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/books/index.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Foundation | Welcome</title>
</head>
 <div class="orbit" role="region" aria-label="Favorite Space Pictures">
<ul class="orbit-container" data-orbit>
<button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
<button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
<li class="orbit-slide is-active">
<img src="http://ldsearthstewardship.org/wp-content/uploads/2012/09/books.jpg" width="1500"
height="750">
</li>
<li class="orbit-slide">
<img src="http://cdn.www.duarte.com/wp-content/uploads/2010/03/Book_Cover_word_people.jpg" width="1500"
height="750">
</li>
<li class="orbit-slide">
<img src="https://s-media-cache-ak0.pinimg.com/236x/fd/16/54/fd1654e603e5e91d5fee86422fc6efc2.jpg" width="1500"
height="750">
</li>
<li class="orbit-slide">
<img src="https://www.washingtonpost.com/graphics/entertainment/best-books-of-2015/img/wp_readers_update.png" width="1500"
height="750">
</li>
</ul>
</div>
<div class="row column text-center">


<h2>Newest Releases!</h2>
<hr>
</div>
<div class="row small-up-2 large-up-4">
<% @books.each do |book| %>
<div class="column">
<%= link_to image_tag(book.poster_url), book_path(book), :class => 'thumbnail', :method => 'get' %>
<h5><b><%= book.title %></b>
by <%= book.author %>
</h5>
<b><p>$<%=book.price%></p></b>
<a href="/cart/<%= book.id %>" class="button expanded">Move to cart</a>
</div>
<% end %>

<hr>
<div class="row column">
<div class="callout primary">

</div>
</div>
<hr>
<div class="row column text-center">
<h2>Magazines 2016</h2>
<hr>
</div>
<div class="row small-up-2 medium-up-3 large-up-6">
<div class="column">
<img class="thumbnail" src="https://s-media-cache-ak0.pinimg.com/736x/b6/43/c6/b643c616e15262970aae0e410b460e6f.jpg" width="300" height="400">
<h5>The business magazine 2016 </h5>
<b><p>$60</p></b>
<!-- <a href="#" class="button small expanded hollow">Move to cart</a> -->
</div>
<div class="column">
<img class="thumbnail" src="http://www.pdfmagaz.in/wp-content/uploads/2016/01/15/diesel-tech-magazine-winter-2016/Diesel-Tech-Magazine-Winter-2016.jpg" width="300" height="400">
<h5>Deisel tech</h5>
<b><p>$150</p></b>
<!-- <a href="#" class="button small expanded hollow">Move to cart</a> -->
</div>
<div class="column">
<img class="thumbnail" src="http://downmagaz.com/uploads/posts/2016-01/1451802682_tech__learning_2016_01_downmagaz.jpg" width="300" height="400">
<h5>Tech&Learning</h5>
<b><p>$80</p></b>
<!-- <a href="#" class="button small expanded hollow">Move to cart</a> -->
</div>
<div class="column">
<img class="thumbnail" src="http://downmagaz.com/uploads/posts/2016-01/1452843596_historic-racing-technology-winter-2016_downmagaz.com.jpg">
<h5>History Racing Tech</h5>
<b><p>$60</p></b>
<!-- <a href="#" class="button small expanded hollow">Move to cart</a> -->
</div>
<div class="column">
<img class="thumbnail" src="http://thebook-mark.com/magazines/uploads/posts/2015-11/thumbs/1448900745_7017.jpg">
<h5>Tech Advisor</h5>
<b><p>$120</p></b>
<!-- <a href="#" class="button small expanded hollow">Move to cart</a> -->
</div>
<div class="column">
<img class="thumbnail" src="http://d3lp4xedbqa8a5.cloudfront.net/s3/digital-cougar-assets/BauerCorporate/2015/05/11/1616/0006091_good-health.jpeg" width="300" height="400">
<h5>Good Health</h5>
<b><p>$130</p></b>
<!-- <a href="#" class="button small expanded hollow">Move to cart</a> -->
</div>
</div>
<hr>
<div class="row">
<div class="medium-4 columns">
<h4>BestReads 2015</h4>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://www.kateatkinson.co.uk/upld/tt/timthumb.php?src=upld/jackets/AGIR_US_e4988a19d162.jpg&q=81&w=600&h=900&zc=0" width="100" height="100">
</div>
<div class="media-object-section">
<h5><b>A God in Ruins</b> by Kate Atkinson</h5>
<p2>Atkinson covers four generations of the Todd family that was at the center of her novel, Life After Life. The narrative jumps throughout the 20th century around the story of Teddy Todd, a Royal Air Force pilot in World War II who struggles with his postwar survival.</p2>
</div>
</div>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://www.nealstephenson.com/assets/gallery/3/113.jpg" width="100" height="100">
</div>
<div class="media-object-section">
<h5><b>Seveneves</b> by Neal Stephenson </h5>
<p2>When disaster dooms the planet, people across the world unite to send a coalition into outer space and ensure the survival of their species. After 5,000 years, seven races of humans stem from the survivors, and they attempt to return to a changed earth.</p2>
</div>
</div>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://ecx.images-amazon.com/images/I/41tr2GDzhtL._SX327_BO1,204,203,200_.jpg" width="100" height="100">
</div>
<div class="media-object-section">
<h5><b>I Take You</b> by Eliza Kennedy</h5>
<p2>Lily Wilder, a promiscuous lawyer in New York, prepares to marry her archaeologist fiancé, Will. The novel follows her difficulties embracing monogamy in both theory and practice, told with the inflection of Lily’s humor.</p2>
</div>
</div>
</div>
<div class="medium-4 columns">
<h4>BestReads 2015 </h4>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://ecx.images-amazon.com/images/I/514Qc9qdPHL._SX325_BO1,204,203,200_.jpg" width="100" height="100">
</div>
<div class="media-object-section">
<h5><b>Get in Trouble</b> by Kelly Link</h5>
<p2>Each of these nine stories takes place in a seemingly normal setting, such as a hotel or at a birthday party, into which dark elements of the fantastic and supernatural subtly intrude.</p2>
</div>
</div>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://www.rarshare.com/wp-content/uploads/2015/03/51F4L8SwzBL._SY300_.jpg" width="100" height="100">
</div>
<div class="media-object-section">
<h5><b>Trigger Warning</b> by Neil Gaiman </h5>
<p2>A collection of tales from virtuoso storyteller Neil Gaiman, ranging from horror to science fiction to fairy tales to verse. They include “adventure story,” Gaiman’s rumination on death, and “a calendar of tales,” short takes inspired by his replies to fan tweets. </p2>
</div>
</div>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://i0.wp.com/www.casualoptimist.com/wp-content/uploads/2014/07/H-Is-For-Hawk.jpg" width="100" height="100">
</div>
<div class="media-object-section">
<h5><b>H is for Hawk</b> by Helen Macdonald</h5>
<p2>An experienced falconer, Macdonald resolves to train a vicious predator, the goshawk, as a means to cope with the death of her father. This stunning memoir explores the deep strange bond she forms with her bird.</p2>
</div>
</div>
</div>
<div class="medium-4 columns">
<h4>BestReads 2015</h4>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://i.telegraph.co.uk/multimedia/archive/03255/alice7_3255945f.jpg" width="100" height="100">
</div>
<div class="media-object-section">
<h5><b>The Story of Alice</b> by Robert Douglas-Fairhurst</h5>
<p2>The Story of Alice charts the curious, controversial friendship between Oxford mathematician Charles Dodgson (more commonly known as Lewis Carroll) and Alice Liddell, the child for whom he created Alice in Wonderland. The book also explores how and why Alice in Wonderland and its sequel, Through the Looking Glass, have had such lasting cultural resonance.</p2>
</div>
</div>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://images.randomhouse.com/cover/9781594632648" width="100" height="100">
</div>
<div class="media-object-section">
<h5><b>The brothers</b> by masha gessen</h5>
<p2>Russian-American journalist Masha Gessen’s passionate, opinionated, deeply reported exploration of the long road that led the Tsarnaev brothers to commit the Boston Marathon bombing. She traces the family’s history from Chechnya to a precarious Boston-area immigrant demi-monde, asking urgent questions and avoiding simple answers. </p2>
</div>
</div>
<div class="media-object">
<div class="media-object-section">
<img class="thumbnail" src="http://images.randomhouse.com/cover/9780804171441" width="100" height="180">
</div>
<div class="media-object-section">
<h5><b>The folded clock</b> by heidi julavits</h5>
<p2>Inspired by diaries from her childhood, Heidi Julavits chronicles her daily life in this diary-form memoir that is simultaneously about small details and big ideas. </p2>
</div>
</div>
</div>
</div>
<div class="callout large secondary">
<div class="row">
<div class="large-4 columns">
<b><h4>Power and importance of reading</h4></b>
<p2>The biggest pleasure comes from what we read, not from on what we read.
The real difference, though, lies in our attitude to reading. Gilbert K. Chesterton once said: “There is a great deal of difference between an eager man who wants to read a book and the tired man who wants a book to read.”</p2>
</div>
</div>


</div>
</body>
</html>

app/views/books/new.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :author %>:
  <%= f.text_field :author %><br />

  <%= f.label :price %>:
  <%= f.text_field :price %><br />

  <%= f.label :poster_url %>:
  <%= f.text_field :poster_url %><br />

  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Poster url:</strong>
  <%= @book.poster_url %>
</p>




<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Delete',book_path(@book), :method => 'delete' %> |
<%= link_to 'Back', books_path %>

app/views/cart/index.html.erb
<h2>Your Cart!</h2>
<h5><%= link_to 'Empty Your Cart' , cart_clear_path %></h5>
<br><br><br>

<% total = 0 %>

<ul>

<% @cart.each do | id, quantity | %>
    <% book = Book.find(id) %>
    <li>
     <b><h6><%= link_to book.title, book  %></b></h6>
     <p><%= book.author %></p>
     <p><%= number_to_currency(book.price, :unit => '$') %></p>
     <p>Quantity: <%= quantity %></p>
    </li>
    <h2><% total += quantity * book.price %></h2>
<% end %>
<p><b><h4><%= number_to_currency(total, :unit => '$') %></h4></b></p>
</ul>
<style>
h2, h5{
	text-align: center;
}
</style>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_header.html.erb
<head>
<%= csrf_meta_tags %>
</head>


<div class="row">
  <nav class="top-bar column" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1>
            <a href="/">
              <i class="fi-book-bookmark"></i> BoOkStore
            </a>
          </h1>
        </li>
      </ul>

      <section class="top-bar-section">
      <div id="tabs">
        <ul>

        <%if current_user%>

        <% if user_signed_in? %>

            <div><h5><%= "Welcome #{current_user.email}" %></h5></div>
        <% end %>
          <li>
                 <%= link_to cart_path do%>
                 <i class="fi-shopping-cart"></i>
                 My Cart
                 (<span class="cart-count"><%=session[:cart].length if session[:cart]%></span>)
                 <%end%>
          </li>
                <li>
               <%=link_to "Add New Book", new_book_path%></li>
               <li><%= link_to "Admin Controls", rails_admin_path %></li>
              <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li><br>


                <li><i class="fi-home"></i><%= link_to "Home", root_path %><br></li>

                <li><i class="fi-widget"></i>
                <%= link_to "About", page_about_path %><br></li>
                <li><i class="fi-torsos-all"></i>
                <%= link_to "FAQs", page_faqs_path %><br></li>
                <li><i class="fi-address-book"></i>
                <%= link_to "Contact Us", page_contact_path %><br><br></li>
                
 

        <%else%>
              <li><%=link_to "Register", new_user_registration_path %></li>
              
                <%end%>

        </ul>
        </div>
      </section>

    </nav>
</div>

app/views/layouts/application.html.erb
<body>
<%= csrf_meta_tag %> 
  <%= render "layouts/header" %>

  <%= render "layouts/alerts" %>

  <div id="main-content" class="row full-min-height">
    <%= yield %>
  </div>

  <footer class="row">
    <div class="large-12 columns">
      <hr> <p>© BoOkStore 2016</p>
      <h1 style="text-align:right;">
            <img src="http://s.gr-assets.com/assets/home/headline-e2cd420e71737ff2815d09af5b65c4e4.png" alt="http://s.gr-assets.com/assets/home/headline-e2cd420e71737ff2815d09af5b65c4e4.png" width="150" height="142"></h1>
    </div>
  </footer>


  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application" %>
</body>

app/views/page/about.html.erb
<p5>
<h5><b>The right book in the right hands at the right time
can change the world.</b></h5>
<h5>Who We Are</h5><br>
Goodreads is the world’s largest site for readers and book recommendations. Our mission is to help people find and share books they love. Goodreads launched in January 2007.<br>

<h5>Our Team »</h5><br>
A Few Things You Can Do On Goodreads
See which books your friends are reading.
Track the books you're reading, have read, and want to read.
Check out your personalized book recommendations. Our recommendation engine analyzes 20 billion data points to give suggestions tailored to your literary tastes.
Find out if a book is a good fit for you from our community’s reviews.<br>


<h5>A Message From Our CEO and Co-Founder</h5><br>
When I was in second grade, I discovered the Hardy Boys series. Ever since, I've loved to read — both for fun and to improve my mind. And I'm always looking for the next great book.

One afternoon while I was scanning a friend's bookshelf for ideas, it struck me: when I want to know what books to read, I'd rather turn to a friend than any random person or bestseller list.

So I decided to build a website – a place where I could see my friends' bookshelves and learn about what they thought of all their books. Elizabeth, my co-founder (and now my wife) wrote the site copy and I wrote the code. We started in my living room, motivated by the belief that there was a better way to discover and discuss good books, and that we could build it.

<p>Goodreads is that site. It is a place where you can see what your friends are reading and vice versa. You can create "bookshelves" to organize what you've read (or want to read). You can comment on each other's reviews. You can find your next favorite book. And on this journey with your friends you can explore new territory, gather information, and expand your mind.</p>

<h5><b>Knowledge is power, and power is best shared among readers.</h5></b></p5><br>

Otis Chandler<br>
CEO and Co-Founder

app/views/page/contact.html.erb
<form id="contact_form" action="send_details" method="POST" enctype="multipart/form-data">
  <div class="row">
    <label for="name">Your name:</label><br />
    <input id="name" class="input" name="name" type="text" value="" size="30" /><br />
  </div>
  <div class="row">
    <label for="email">Your email:</label><br />
    <input id="email" class="input" name="email" type="text" value="" size="30" /><br />
  </div>
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
  <div class="row">
    <label for="message">Your message:</label><br />
    <textarea id="message" class="input" name="message" rows="7" cols="30"></textarea><br />
  </div>
  <input id="submit_button" type="submit" value="Send email" />
</form>           

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :poster_url %><br>
    <%= f.text_field :poster_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th>Poster url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.author %></td>
        <td><%= product.price %></td>
        <td><%= product.poster_url %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><a href="/cart/<%= product.id %>"> Add To Cart</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @product.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Poster url:</strong>
  <%= @product.poster_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>